//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX_PullingWrong
    {
        public int WrongID { get; set; }
        public string OpenId { get; set; }
        public int QuesId { get; set; }
        public string WrongType { get; set; }
        public string Remarks { get; set; }
        public System.DateTime WrongDate { get; set; }
    }
}
